### PR TITLE
API Break;

### LINKED ISSUE #5: error
Server thread/CRITICAL Could not pass event 'pocketmine\event\player\PlayerDeathEvent' to 'Bounty v1.0.2': Call to undefined method pocketmine\event\entity\EntityDamageEvent::getDamager() on Jack\Bounty\Main
25.08 16:29:31 [Server] Server thread/CRITICAL Error: "Call to undefined method pocketmine\event\entity\EntityDamageEvent::getDamager()" (EXCEPTION) in "Bounty-master/src/Jack/Bounty/Main" at line 138
25.08 16:29:31 [Server] Server thread/DEBUG #0 src/pocketmine/plugin/MethodEventExecutor(38): Jack\Bounty\Main->onDeath(pocketmine\event\player\PlayerDeathEvent object)
25.08 16:29:31 [Server] Server thread/DEBUG #1 src/pocketmine/plugin/RegisteredListener(98): pocketmine\plugin\MethodEventExecutor->execute(Jack\Bounty\Main object, pocketmine\event\player\PlayerDeathEvent object)
25.08 16:29:31 [Server] Server thread/DEBUG #2 src/pocketmine/plugin/PluginManager(752): pocketmine\plugin\RegisteredListener->callEvent(pocketmine\event\player\PlayerDeathEvent object)
25.08 16:29:31 [Server] Server thread/DEBUG #3 src/pocketmine/Player(3619): pocketmine\plugin\PluginManager->callEvent(pocketmine\event\player\PlayerDeathEvent object)
25.08 16:29:31 [Server] Server thread/DEBUG #4 src/pocketmine/entity/Living(594): pocketmine\Player->onDeath()
25.08 16:29:31 [Server] Server thread/DEBUG #5 src/pocketmine/Player(3497): pocketmine\entity\Living->kill()
25.08 16:29:31 [Server] Server thread/DEBUG #6 src/pocketmine/entity/Entity(952): pocketmine\Player->kill()
25.08 16:29:31 [Server] Server thread/DEBUG #7 src/pocketmine/entity/Living(129): pocketmine\entity\Entity->setHealth(double 0)
25.08 16:29:31 [Server] Server thread/DEBUG #8 src/pocketmine/entity/Entity(898): pocketmine\entity\Living->setHealth(double 0)
25.08 16:29:31 [Server] Server thread/DEBUG #9 src/pocketmine/entity/Living(532): pocketmine\entity\Entity->attack(pocketmine\event\entity\EntityDamageEvent object)
25.08 16:29:31 [Server] Server thread/DEBUG #10 src/pocketmine/Player(3704): pocketmine\entity\Living->attack(pocketmine\event\entity\EntityDamageEvent object)
25.08 16:29:31 [Server] Server thread/DEBUG #11 src/pocketmine/entity/Entity(1014): pocketmine\Player->attack(pocketmine\event\entity\EntityDamageEvent object)
25.08 16:29:31 [Server] Server thread/DEBUG #12 src/pocketmine/entity/Living(630): pocketmine\entity\Entity->entityBaseTick(integer 1)
25.08 16:29:31 [Server] Server thread/DEBUG #13 src/pocketmine/entity/Human(633): pocketmine\entity\Living->entityBaseTick(integer 1)
25.08 16:29:31 [Server] Server thread/DEBUG #14 src/pocketmine/Player(1704): pocketmine\entity\Human->entityBaseTick(integer 1)
25.08 16:29:31 [Server] Server thread/DEBUG #15 src/pocketmine/level/Level(743): pocketmine\Player->onUpdate(integer 7491)
25.08 16:29:31 [Server] Server thread/DEBUG #16 src/pocketmine/Server(2359): pocketmine\level\Level->doTick(integer 7491)
25.08 16:29:31 [Server] Server thread/DEBUG #17 src/pocketmine/Server(2516): pocketmine\Server->checkTickUpdates(integer 7491, double 1535214571.0261)
25.08 16:29:31 [Server] Server thread/DEBUG #18 src/pocketmine/Server(2258): pocketmine\Server->tick()
25.08 16:29:31 [Server] Server thread/DEBUG #19 src/pocketmine/Server(2132): pocketmine\Server->tickProcessor()
25.08 16:29:31 [Server] Server thread/DEBUG #20 src/pocketmine/Server(1713): pocketmine\Server->start()
25.08 16:29:31 [Server] Server thread/DEBUG #21 src/pocketmine/PocketMine(237): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /, string /plugins/)
25.08 16:29:31 [Server] Server thread/DEBUG #22 /pmmp_1269_1.5.0.phar(1): require(string phar:///pmmp_1269_1.5.0.phar/src/pocketmine/PocketMine.php)

### PR DESCRIPTION
**Pull request by iZeaoGamer**
Hi. This issue should fix: the rename from getDamager() to getModifier(). This was a API break that pocketmine have done over the past few weeks or months, and I just thought I'd update it to that API, and make sure to update all the plugin's problems and issues I see.
This has not been tested yet however, you may want to test this commit before merging.
If more errors occur, please let me know, and I'll do more testing myself to double check that this issue get's resolved.
## UPDATES ##
The updates which consists:
Updating the propertie's code (onDeath) event, to double check that getModifier is now involved and added, instead of getDamager(), the pre-resistance bug which has occurred for a while, and should now be fixed.
This issue should also fix: #5 
If there's anything else I need to change, then please let me know.
Thank you.

### CODE REVIEW

**Comment by JaxkDev** [comment]
Hi, most of my plugins have gone private to the server I now work on, but I do still accept PR’s on public work.
I will need to test this first, I’ll get back to you when I have.

**Comment by iZeaoGamer** [comment]
Okay, thanks.

**Comment by iZeaoGamer** [comment]
I just noticed getDamager() is different to getModifier(). I've tested similar plugins that has this part of the code and they seem to work just fine. I'm not entirely sure what happened, but this PR should fix everything relating to the issue posts you were receiving.
Let's just see how this plays out, and let me know if this fixes it or not. Thanks.
And sorry for any confusions there.

**Comment by JaxkDev** [comment]
I’ll test this version also, but in reality I need to rewrite the whole plugin at some point.

**Comment by iZeaoGamer** [comment]
Alright.

**Comment by JaxkDev** [comment]
Tests were run on latest pmmp server, and the death of someone with a valid bounty failed no message or logged message by plugin, I can only assume $cause was not of player instance.

**Comment by JaxkDev** [comment]
So I had some time to myself and read the breaks,
I found that all I have to do is change getPlayer to getEntity.

**Pull request closed without merging**
